# @package _global_
defaults:
  - _self_
  - model: conv
  - data: mnist
  - optim: adam

  - experiment: null

  - override hydra/job_logging: custom

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 3
#  precision: 16

cwd: ${hydra:runtime.cwd}
wandb_project: "masters-thesis"
seed: null

hydra:
  run:
    dir: logs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true
    env_set:
      # currently there are some issues with running sweeps alongside wandb
      # https://github.com/wandb/client/issues/1314
      # this env var fixes that
      WANDB_START_METHOD: thread
